/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project.uas;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Kelompok 12 Syauqi & Sovia
 */
public class formKonversiData extends javax.swing.JFrame {

    /**
     * Creates new form formKonversiData
     */
    private boolean isTfData1Focused = true;
    private boolean isTfData2Focused = false;

    public formKonversiData() {
        initComponents();
        tfData1.setText("0");
        cBoxData1.setSelectedItem("Megabyte MB");
        cBoxData2.setSelectedItem("Kilobyte KB");

        btnSamadengan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    btnSamadenganActionPerformed(new java.awt.event.ActionEvent(btnSamadengan, 0, ""));
                }
            }
        });

        tfData1.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (tfData1.getText().equals("0")) {
                    tfData1.setText("");
                }
                isTfData1Focused = true;
                isTfData2Focused = false;
            }
        });

        tfData2.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (tfData2.getText().equals("0")) {
                    tfData2.setText("");
                }

                isTfData1Focused = false;
                isTfData2Focused = true;
            }
        });

        convertData();
        tfData1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                convertData1ToData2();
            }
        });

        tfData2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                convertData2ToData1();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnAC = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnKoma = new javax.swing.JButton();
        cBoxData1 = new javax.swing.JComboBox<>();
        cBoxData2 = new javax.swing.JComboBox<>();
        tfData1 = new javax.swing.JTextField();
        tfData2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblData1 = new javax.swing.JLabel();
        lblData2 = new javax.swing.JLabel();
        btnSamadengan = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btnAC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAC.setForeground(new java.awt.Color(255, 51, 0));
        btnAC.setText("AC");
        btnAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnACActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 102, 0));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btn5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn0.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btnKoma.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnKoma.setText(",");
        btnKoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKomaActionPerformed(evt);
            }
        });

        cBoxData1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Byte B", "Kilobyte KB", "Megabyte MB", "Gigabyte GB", "Terabyte TB", "Petabyte PB", " " }));
        cBoxData1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxData1ActionPerformed(evt);
            }
        });

        cBoxData2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Byte B", "Kilobyte KB", "Megabyte MB", "Gigabyte GB", "Terabyte TB", "Petabyte PB", " " }));
        cBoxData2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxData2ActionPerformed(evt);
            }
        });

        tfData1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfData1ActionPerformed(evt);
            }
        });

        tfData2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfData2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel3.setText("KONVERSI DATA");

        lblData1.setText("Megabyte");

        lblData2.setText("Kilobyte");

        btnSamadengan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSamadengan.setForeground(new java.awt.Color(255, 102, 0));
        btnSamadengan.setText("=");
        btnSamadengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSamadenganActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblData2)
                            .addComponent(lblData1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(btn0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnKoma, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnAC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSamadengan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cBoxData2, 0, 119, Short.MAX_VALUE)
                                    .addComponent(cBoxData1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfData1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(tfData2)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(109, 109, 109)))))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBoxData1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfData1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblData1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBoxData2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfData2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblData2)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnKoma, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSamadengan, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAC, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        addDigitToInput("3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btnKomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKomaActionPerformed
        // TODO add your handling code here:
        if (isTfData1Focused) {
            String currentText = tfData1.getText();
            tfData1.setText(currentText + ".");
        } else if (isTfData2Focused) {
            String currentText = tfData2.getText();
            tfData2.setText(currentText + ".");
        }
    }//GEN-LAST:event_btnKomaActionPerformed

    private void cBoxData2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxData2ActionPerformed
        convertData();
        updateLabels();
    }//GEN-LAST:event_cBoxData2ActionPerformed

    private void cBoxData1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxData1ActionPerformed
        convertData();
        updateLabels();
    }//GEN-LAST:event_cBoxData1ActionPerformed

    private void tfData1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfData1ActionPerformed
        // TODO add your handling code here:
        convertData();
    }//GEN-LAST:event_tfData1ActionPerformed

    private void tfData2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfData2ActionPerformed
        // TODO add your handling code here:
        convertData();
    }//GEN-LAST:event_tfData2ActionPerformed

    private void btnACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnACActionPerformed
        // TODO add your handling code here:
        resetToDefault();
    }//GEN-LAST:event_btnACActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        deleteCharacter();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSamadenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSamadenganActionPerformed
        // TODO add your handling code here:
        if (isTfData1Focused) {
            convertData1ToData2();
        } else if (isTfData2Focused) {
            convertData2ToData1();
        }
    }//GEN-LAST:event_btnSamadenganActionPerformed

    private void addDigitToInput(String digit) {
        if (isTfData1Focused) {
            String currentText = tfData1.getText();
            if (currentText.equals("0")) {
                tfData1.setText(digit);
            } else {
                tfData1.setText(currentText + digit);
            }
        } else if (isTfData2Focused) {
            String currentText = tfData2.getText();
            if (currentText.equals("0")) {
                tfData2.setText(digit);
            } else {
                tfData2.setText(currentText + digit);
            }
        }
    }

    private void handleButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String buttonText = ((javax.swing.JButton) evt.getSource()).getText();
        addDigitToInput(buttonText);
    }


    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        handleButtonActionPerformed(evt);
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        handleButtonActionPerformed(evt);
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        handleButtonActionPerformed(evt);
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        handleButtonActionPerformed(evt);
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        handleButtonActionPerformed(evt);
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        handleButtonActionPerformed(evt);
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        handleButtonActionPerformed(evt);
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        handleButtonActionPerformed(evt);
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
        handleButtonActionPerformed(evt);
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        kembaliKeFormUtama();
    }//GEN-LAST:event_btnBackActionPerformed

    private void kembaliKeFormUtama() {
        // Close the current form (formKonversiData)
        this.dispose();

        // Create and display the formUtama
        FormUtama formUtama = new FormUtama();
        formUtama.setVisible(true);
    }

    private void deleteCharacter() {
        if (isTfData1Focused) {
            // Hapus satu karakter dari tfData1
            String data1Text = tfData1.getText();
            if (data1Text.length() > 0) {
                data1Text = data1Text.substring(0, data1Text.length() - 1);
                tfData1.setText(data1Text);
            }
        } else if (isTfData2Focused) {
            // Hapus satu karakter dari tfData2
            String data2Text = tfData2.getText();
            if (data2Text.length() > 0) {
                data2Text = data2Text.substring(0, data2Text.length() - 1);
                tfData2.setText(data2Text);
            }
        }
    }

    private void resetToDefault() {
        // Reset text fields and combo boxes to default values
        tfData1.setText("0");
        tfData2.setText("");
    }

    private void convertData() {
        String selectedUnit1 = (String) cBoxData1.getSelectedItem();
        String selectedUnit2 = (String) cBoxData2.getSelectedItem();

        String data1Text = tfData1.getText();

        try {
            float data1Value = Float.parseFloat(data1Text);
            float convertedValue = convert(data1Value, selectedUnit1, selectedUnit2);
            tfData2.setText(Float.toString(convertedValue));
        } catch (NumberFormatException e) {
            // Tangani kesalahan jika input tidak valid
            tfData2.setText("Invalid Input");
        }
    }

    private String previousLabel2;
    
    private void updateLabels() {
        String selectedUnit1 = (String) cBoxData1.getSelectedItem();
        String selectedUnit2 = (String) cBoxData2.getSelectedItem();

        lblData1.setText(selectedUnit1);
        lblData2.setText(selectedUnit2);

        String label1 = lblData1.getText();
        String label2 = lblData2.getText();
        
        if (label1.equals(label2)) {
            JOptionPane.showMessageDialog(this, "Unit selections tidak boleh sama", "Error", JOptionPane.ERROR_MESSAGE);
            cBoxData2.setSelectedItem(previousLabel2);
            String selected = (String) cBoxData2.getSelectedItem();
            lblData2.setText(selected);
        }else{
            previousLabel2 = label2;
        }
    }


    private float convert(float value, String unit1, String unit2) {
        // Definisikan faktor konversi untuk unit yang berbeda
        float byteToKilobyte = 1f / 1024;
        float byteToMegabyte = byteToKilobyte / 1024;
        float byteToGigabyte = byteToMegabyte / 1024;
        float byteToTerabyte = byteToGigabyte / 1024;
        float byteToPetabyte = byteToTerabyte / 1024;

        // Faktor konversi dari Megabyte (MB) ke unit lain
        float megabyteToKilobyte = 1024;
        float megabyteToGigabyte = 1f / 1024;
        float megabyteToTerabyte = megabyteToGigabyte / 1024;
        float megabyteToPetabyte = megabyteToTerabyte / 1024;

        // Faktor konversi dari Gigabyte (GB) ke unit lain
        float gigabyteToKilobyte = megabyteToKilobyte * 1024;
        float gigabyteToMegabyte = 1024;
        float gigabyteToTerabyte = 1f / 1024;
        float gigabyteToPetabyte = gigabyteToTerabyte / 1024;

        // Faktor konversi dari Terabyte (TB) ke unit lain
        float terabyteToKilobyte = gigabyteToKilobyte * 1024;
        float terabyteToMegabyte = gigabyteToMegabyte * 1024;
        float terabyteToGigabyte = gigabyteToTerabyte * 1024;
        float terabyteToPetabyte = 1f / 1024;

        // Faktor konversi dari Petabyte (PB) ke unit lain
        float petabyteToKilobyte = terabyteToKilobyte * 1024;
        float petabyteToMegabyte = terabyteToMegabyte * 1024;
        float petabyteToGigabyte = terabyteToGigabyte * 1024;
        float petabyteToTerabyte = terabyteToPetabyte * 1024;
        float petabyteToByte = byteToPetabyte;

        // Faktor konversi dari Kilobyte (KB) ke unit lain
        float kilobyteToMegabyte = 1f / 1024;
        float kilobyteToGigabyte = kilobyteToMegabyte / 1024;
        float kilobyteToTerabyte = kilobyteToGigabyte / 1024;
        float kilobyteToPetabyte = kilobyteToTerabyte / 1024;

        // Hitung hasil konversi berdasarkan unit yang dipilih
        if (unit1.equals("Byte B") && unit2.equals("Kilobyte KB")) {
            return value * byteToKilobyte;
        } else if (unit1.equals("Byte B") && unit2.equals("Megabyte MB")) {
            return value * byteToMegabyte;
        } else if (unit1.equals("Byte B") && unit2.equals("Gigabyte GB")) {
            return value * byteToGigabyte;
        } else if (unit1.equals("Byte B") && unit2.equals("Terabyte TB")) {
            return value * byteToTerabyte;
        } else if (unit1.equals("Byte B") && unit2.equals("Petabyte PB")) {
            return value * byteToPetabyte;
        } else if (unit1.equals("Kilobyte KB") && unit2.equals("Byte B")) {
            return value / byteToKilobyte;
        } else if (unit1.equals("Kilobyte KB") && unit2.equals("Megabyte MB")) {
            return value * kilobyteToMegabyte;
        } else if (unit1.equals("Kilobyte KB") && unit2.equals("Gigabyte GB")) {
            return value * kilobyteToGigabyte;
        } else if (unit1.equals("Kilobyte KB") && unit2.equals("Terabyte TB")) {
            return value * kilobyteToTerabyte;
        } else if (unit1.equals("Kilobyte KB") && unit2.equals("Petabyte PB")) {
            return value * kilobyteToPetabyte;
        } else if (unit1.equals("Megabyte MB") && unit2.equals("Kilobyte KB")) {
            return value / kilobyteToMegabyte;
        } else if (unit1.equals("Megabyte MB") && unit2.equals("Gigabyte GB")) {
            return value * megabyteToGigabyte;
        } else if (unit1.equals("Megabyte MB") && unit2.equals("Terabyte TB")) {
            return value * megabyteToTerabyte;
        } else if (unit1.equals("Megabyte MB") && unit2.equals("Petabyte PB")) {
            return value * megabyteToPetabyte;
        } else if (unit1.equals("Gigabyte GB") && unit2.equals("Kilobyte KB")) {
            return value / kilobyteToGigabyte;
        } else if (unit1.equals("Gigabyte GB") && unit2.equals("Megabyte MB")) {
            return value / megabyteToGigabyte;
        } else if (unit1.equals("Gigabyte GB") && unit2.equals("Terabyte TB")) {
            return value * gigabyteToTerabyte;
        } else if (unit1.equals("Gigabyte GB") && unit2.equals("Petabyte PB")) {
            return value * gigabyteToPetabyte;
        } else if (unit1.equals("Terabyte TB") && unit2.equals("Kilobyte KB")) {
            return value / kilobyteToTerabyte;
        } else if (unit1.equals("Terabyte TB") && unit2.equals("Megabyte MB")) {
            return value / megabyteToTerabyte;
        } else if (unit1.equals("Terabyte TB") && unit2.equals("Gigabyte GB")) {
            return value / gigabyteToTerabyte;
        } else if (unit1.equals("Terabyte TB") && unit2.equals("Petabyte PB")) {
            return value * terabyteToPetabyte;
        } else if (unit1.equals("Petabyte PB") && unit2.equals("Kilobyte KB")) {
            return value / kilobyteToPetabyte;
        } else if (unit1.equals("Petabyte PB") && unit2.equals("Megabyte MB")) {
            return value / megabyteToPetabyte;
        } else if (unit1.equals("Petabyte PB") && unit2.equals("Gigabyte GB")) {
            return value / gigabyteToPetabyte;
        } else if (unit1.equals("Petabyte PB") && unit2.equals("Terabyte TB")) {
            return value / terabyteToPetabyte;
        } else if (unit1.equals("Petabyte PB") && unit2.equals("Byte B")) {
            return value * petabyteToByte;
        }

        return value; // Jika unit tidak berubah, kembalikan nilai asli
    }

    private void convertData1ToData2() {
        String selectedUnit1 = (String) cBoxData1.getSelectedItem();
        String selectedUnit2 = (String) cBoxData2.getSelectedItem();

        String data1Text = tfData1.getText();

        try {
            float data1Value = Float.parseFloat(data1Text);
            float convertedValue = convert(data1Value, selectedUnit1, selectedUnit2);
            tfData2.setText(Float.toString(convertedValue));
        } catch (NumberFormatException e) {
            tfData2.setText("Invalid Input");
        }
    }

    private void convertData2ToData1() {
        String selectedUnit1 = (String) cBoxData1.getSelectedItem();
        String selectedUnit2 = (String) cBoxData2.getSelectedItem();

        String data2Text = tfData2.getText();

        try {
            float data2Value = Float.parseFloat(data2Text);
            float convertedValue = convert(data2Value, selectedUnit2, selectedUnit1);
            tfData1.setText(Float.toString(convertedValue));
        } catch (NumberFormatException e) {
            tfData1.setText("Invalid Input");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formKonversiData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formKonversiData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formKonversiData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formKonversiData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formKonversiData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAC;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnKoma;
    private javax.swing.JButton btnSamadengan;
    private javax.swing.JComboBox<String> cBoxData1;
    private javax.swing.JComboBox<String> cBoxData2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblData1;
    private javax.swing.JLabel lblData2;
    private javax.swing.JTextField tfData1;
    private javax.swing.JTextField tfData2;
    // End of variables declaration//GEN-END:variables
}
