package project.uas;

import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class formKonversiPanjang extends javax.swing.JFrame {

    public boolean leftSelect = true;

    public formKonversiPanjang() {
        initComponents();

        jBox2.setSelectedItem("Hm (Hektometer)");
        jBox1.setSelectedItem("Km (Kilometer)");
        this.jTisi.setEditable(false);
        this.jisi.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBack = new javax.swing.JButton();
        jlversi = new javax.swing.JLabel();
        jBox1 = new javax.swing.JComboBox<>();
        jTisi = new javax.swing.JTextField();
        jBox2 = new javax.swing.JComboBox<>();
        jisi = new javax.swing.JTextField();
        jkonvers = new javax.swing.JButton();
        jB7 = new javax.swing.JButton();
        jB8 = new javax.swing.JButton();
        jB9 = new javax.swing.JButton();
        jB6 = new javax.swing.JButton();
        jB4 = new javax.swing.JButton();
        jB1 = new javax.swing.JButton();
        jB5 = new javax.swing.JButton();
        jB2 = new javax.swing.JButton();
        jbKoma = new javax.swing.JButton();
        jB0 = new javax.swing.JButton();
        jB3 = new javax.swing.JButton();
        jBDelete = new javax.swing.JButton();
        jBac = new javax.swing.JButton();
        panah = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(116, 155, 194));

        jBack.setBackground(new java.awt.Color(241, 246, 249));
        jBack.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jBack.setText("BACK");
        jBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(197, 223, 248), 3));
        jBack.setIconTextGap(2);
        jBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackActionPerformed(evt);
            }
        });

        jlversi.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jlversi.setText("KONVERSI PANJANG");

        jBox1.setBackground(new java.awt.Color(241, 246, 249));
        jBox1.setFont(new java.awt.Font("Sitka Small", 0, 12)); // NOI18N
        jBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Km (Kilometer)", "Hm (Hektometer)", "Dam (Dekameter)", "M (Meter)", "Dm (Desimeter)", "Cm (Centimeter)", "Mm (Milimeter)" }));

        jTisi.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTisiActionPerformed(evt);
            }
        });

        jBox2.setBackground(new java.awt.Color(241, 246, 249));
        jBox2.setFont(new java.awt.Font("Sitka Small", 0, 12)); // NOI18N
        jBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Km (Kilometer)", "Hm (Hektometer)", "Dam (Dekameter)", "M (Meter)", "Dm (Desimeter)", "Cm (Centimeter)", "Mm (Milimeter)" }));

        jisi.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jkonvers.setBackground(new java.awt.Color(197, 223, 248));
        jkonvers.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jkonvers.setForeground(new java.awt.Color(0, 102, 153));
        jkonvers.setText("KONVERS");
        jkonvers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jkonversActionPerformed(evt);
            }
        });

        jB7.setBackground(new java.awt.Color(241, 246, 249));
        jB7.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jB7.setText("7");
        jB7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(197, 223, 248)));
        jB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB7ActionPerformed(evt);
            }
        });

        jB8.setBackground(new java.awt.Color(241, 246, 249));
        jB8.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jB8.setText("8");
        jB8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(197, 223, 248)));
        jB8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB8ActionPerformed(evt);
            }
        });

        jB9.setBackground(new java.awt.Color(241, 246, 249));
        jB9.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jB9.setText("9");
        jB9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(197, 223, 248)));
        jB9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB9ActionPerformed(evt);
            }
        });

        jB6.setBackground(new java.awt.Color(241, 246, 249));
        jB6.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jB6.setText("6");
        jB6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(197, 223, 248)));
        jB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB6ActionPerformed(evt);
            }
        });

        jB4.setBackground(new java.awt.Color(241, 246, 249));
        jB4.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jB4.setText("4");
        jB4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(197, 223, 248)));
        jB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB4ActionPerformed(evt);
            }
        });

        jB1.setBackground(new java.awt.Color(241, 246, 249));
        jB1.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jB1.setText("1");
        jB1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(197, 223, 248)));
        jB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB1ActionPerformed(evt);
            }
        });

        jB5.setBackground(new java.awt.Color(241, 246, 249));
        jB5.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jB5.setText("5");
        jB5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(197, 223, 248)));
        jB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB5ActionPerformed(evt);
            }
        });

        jB2.setBackground(new java.awt.Color(241, 246, 249));
        jB2.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jB2.setText("2");
        jB2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(197, 223, 248)));
        jB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB2ActionPerformed(evt);
            }
        });

        jbKoma.setBackground(new java.awt.Color(241, 246, 249));
        jbKoma.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jbKoma.setText(",");
        jbKoma.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(197, 223, 248)));
        jbKoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbKomaActionPerformed(evt);
            }
        });

        jB0.setBackground(new java.awt.Color(241, 246, 249));
        jB0.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jB0.setText("0");
        jB0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(197, 223, 248)));
        jB0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB0ActionPerformed(evt);
            }
        });

        jB3.setBackground(new java.awt.Color(241, 246, 249));
        jB3.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jB3.setText("3");
        jB3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(197, 223, 248)));
        jB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB3ActionPerformed(evt);
            }
        });

        jBDelete.setBackground(new java.awt.Color(197, 223, 248));
        jBDelete.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jBDelete.setForeground(new java.awt.Color(0, 102, 153));
        jBDelete.setText("DELETE");
        jBDelete.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jBDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDeleteActionPerformed(evt);
            }
        });

        jBac.setBackground(new java.awt.Color(197, 223, 248));
        jBac.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jBac.setForeground(new java.awt.Color(0, 102, 153));
        jBac.setText("AC");
        jBac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBacActionPerformed(evt);
            }
        });

        panah.setFont(new java.awt.Font("Century", 1, 36)); // NOI18N
        panah.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        panah.setText("↓");
        panah.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jBac, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jBDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panah, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jkonvers))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jB1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jB2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jB3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jB0, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbKoma, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jB7, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jB8, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jB9, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jB4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jB5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jB6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBack, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(jlversi))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTisi, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jisi, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBack)
                    .addComponent(jlversi))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panah, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jkonvers))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBac, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB0, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbKoma, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbKomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbKomaActionPerformed
        // TODO add your handling code here:
        if (leftSelect) {
            if (jTisi.getText().length() != 0) {
                jTisi.setText(jTisi.getText() + '.');
            }
        }
    }//GEN-LAST:event_jbKomaActionPerformed

    private void jB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB1ActionPerformed
        // TODO add your handling code here:
        if (leftSelect) {
            jTisi.setText(jTisi.getText() + '1');
        }
    }//GEN-LAST:event_jB1ActionPerformed

    private void jB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB2ActionPerformed
        // TODO add your handling code here:
        if (leftSelect) {
            jTisi.setText(jTisi.getText() + '2');
        }
    }//GEN-LAST:event_jB2ActionPerformed

    private void jB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB3ActionPerformed
        // TODO add your handling code here:
        if (leftSelect) {
            jTisi.setText(jTisi.getText() + '3');
        }
    }//GEN-LAST:event_jB3ActionPerformed

    private void jB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB4ActionPerformed
        // TODO add your handling code here:
        if (leftSelect) {
            jTisi.setText(jTisi.getText() + '4');
        }
    }//GEN-LAST:event_jB4ActionPerformed

    private void jB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB5ActionPerformed
        // TODO add your handling code here:
        if (leftSelect) {
            jTisi.setText(jTisi.getText() + '5');
        }
    }//GEN-LAST:event_jB5ActionPerformed

    private void jB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB6ActionPerformed
        // TODO add your handling code here:
        if (leftSelect) {
            jTisi.setText(jTisi.getText() + '6');
        }
    }//GEN-LAST:event_jB6ActionPerformed

    private void jB7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB7ActionPerformed
        // TODO add your handling code here:
        if (leftSelect) {
            jTisi.setText(jTisi.getText() + '7');
        }
    }//GEN-LAST:event_jB7ActionPerformed

    private void jB8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB8ActionPerformed
        // TODO add your handling code here:
        if (leftSelect) {
            jTisi.setText(jTisi.getText() + '8');
        }
    }//GEN-LAST:event_jB8ActionPerformed

    private void jB9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB9ActionPerformed
        // TODO add your handling code here:
        if (leftSelect) {
            jTisi.setText(jTisi.getText() + '9');
        }
    }//GEN-LAST:event_jB9ActionPerformed

    private void jB0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB0ActionPerformed
        // TODO add your handling code here:
        if (leftSelect) {
            jTisi.setText(jTisi.getText() + '0');
        }
    }//GEN-LAST:event_jB0ActionPerformed

    private void jTisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTisiActionPerformed
        // TODO add your handling code here:
        leftSelect = true;
    }//GEN-LAST:event_jTisiActionPerformed

    private void jBDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDeleteActionPerformed
        // TODO add your handling code here:
        if (leftSelect) {
            String str = jTisi.getText();
            String newstr = str.substring(0, str.length() - 1);
            jTisi.setText(newstr);
        }
    }//GEN-LAST:event_jBDeleteActionPerformed

    private void jBacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBacActionPerformed
        // TODO add your handling code here:
        if (leftSelect) {
            jTisi.setText(null);
            jisi.setText(null);
        }
    }//GEN-LAST:event_jBacActionPerformed

    private void jkonversActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jkonversActionPerformed
        // TODO add your handling code here:
        int operator1 = jBox1.getSelectedIndex();
        int operator2 = jBox2.getSelectedIndex();

        if (operator1 == operator2) {
            JOptionPane.showMessageDialog(this, "Unit selections tidak boleh sama", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Exit the method to avoid further processing
        }

        String inputText = jTisi.getText().trim(); // Trim leading and trailing whitespaces

        if (inputText.isEmpty()) {
            // Handle the case where the input is empty (show an error message, for example)
            JOptionPane.showMessageDialog(this, "Input cannot be empty", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Exit the method
        }

        try {
            float kolom = Float.parseFloat(inputText);
            float result = convertUnits(kolom, operator1, operator2);
            jisi.setText(Float.toString(result)); // Set the result in the jisi field
        } catch (NumberFormatException e) {
            // Handle the case where the input is not a valid float (show an error message, for example)
            JOptionPane.showMessageDialog(this, "Invalid input. Please enter a valid number", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jkonversActionPerformed

    private float convertUnits(float kolom, int operator1, int operator2) {
        float[] multipliers = {1, 10, 100, 1000, 10000, 100000, 1000000};

        if (operator1 == operator2) {
            return kolom; // No conversion needed if the units are the same
        }

        // Calculate the result using the multipliers array
        return kolom * multipliers[operator2] / multipliers[operator1];
    }

    private void jBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackActionPerformed
        // TODO add your handling code here:
        kembaliKeFormUtama();
    }//GEN-LAST:event_jBackActionPerformed

    private void kembaliKeFormUtama() {

        this.dispose();

        FormUtama formUtama = new FormUtama();
        formUtama.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formKonversiPanjang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formKonversiPanjang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formKonversiPanjang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formKonversiPanjang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formKonversiPanjang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB0;
    private javax.swing.JButton jB1;
    private javax.swing.JButton jB2;
    private javax.swing.JButton jB3;
    private javax.swing.JButton jB4;
    private javax.swing.JButton jB5;
    private javax.swing.JButton jB6;
    private javax.swing.JButton jB7;
    private javax.swing.JButton jB8;
    private javax.swing.JButton jB9;
    private javax.swing.JButton jBDelete;
    private javax.swing.JButton jBac;
    private javax.swing.JButton jBack;
    private javax.swing.JComboBox<String> jBox1;
    private javax.swing.JComboBox<String> jBox2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTisi;
    private javax.swing.JButton jbKoma;
    private javax.swing.JTextField jisi;
    private javax.swing.JButton jkonvers;
    private javax.swing.JLabel jlversi;
    private javax.swing.JLabel panah;
    // End of variables declaration//GEN-END:variables
}
